### ISSUE TITLE
FTTI 설명페이지 구현 완료

### ISSUE THREAD

**Issue by boseong-lee** [CSID-DGU/2024-1-OSSProj-ComfyRide-01#40]
담당 : 이보성 (@boseong-lee)
- [x] 사용자의 FTTI를 확인할 수 있는 페이지를 완성했다

**Comment by boseong-lee** [comment]
update explain page  #28

**Comment by Juri-Jang** [comment]
UI 수정 #29

**Comment by Juri-Jang** [comment]
- [x] 이미지 로딩 속도가 느려 이미지 끊김 현상 발생 해결 필요

**Comment by Juri-Jang** [comment]
이미지 로딩 속도 개선함  #61 
1. 페이지 네이션 구현으로 로딩 속도 개선
2. CachedNetworkImage 디펜던시 사용하여 이미지를 캐시에 저장해 두번째 로딩부터 속도 더 빨라질 수 있도록 구현
3. provider 상태관리로 이미지를 미리 로딩할 수있게 구현
