### ISSUE TITLE
FTTI 정의

### ISSUE THREAD

**Issue by Juri-Jang** [CSID-DGU/2024-1-OSSProj-ComfyRide-01#41]
담당 : 이보성 (@boseong-lee)
- [ ] #51

**Comment by boseong-lee** [comment]
FTTI가 형성되기 위한 스타일비율의 경우의수를 CSV로 정립했다.
FTTI 코드 별 축어를 정립하였다.
정립된 CSV파일을 통해 사용자가 선택한 스타일 유형의 유사도를 비교분석하여 FTTI를 생성 한다.

FTTI 유형별 네이밍
https://docs.google.com/spreadsheets/d/1RHXF2otrrtLMZoy-Ar50HZwJB8wpIafJefG2SrEqmPk/edit

콤비네이션
https://drive.google.com/file/d/1QpZzMvw4AjeP8royfD35pFkfXZlQFAMr/view?usp=drive_link

**Comment by boseong-lee** [comment]
15가지 FTTI 코드에 대한 설명과 스타일링팁, 스타일 요약을 CSV에 정리 하였다.
https://docs.google.com/spreadsheets/d/1YfwIN7btJEACOdu_3XbMpTX8twI5PSDI5_Iy-nHtLGQ/edit#gid=0
