### ISSUE TITLE
Github 관리

### ISSUE THREAD

**Issue by Juri-Jang** [CSID-DGU/2024-1-OSSProj-ComfyRide-01#42]
담당 : 김민재 (@Fairy-Slayer)
- [x] README 수정
- - [x] README <-> 산출물 링크 연결
- - [x] Notion 산출물 Github로 옮기기
- - [x] 실행 방법 추가

**Comment by Fairy-Slayer** [comment]
산출물 연결 완료 #45

**Comment by Fairy-Slayer** [comment]
README 수정 완료, 실행방법 추가 완료
#54
