### ISSUE TITLE
신규 유저 페이지 불러오기 오류

### ISSUE THREAD

**Issue by Fairy-Slayer** [CSID-DGU/2024-1-OSSProj-ComfyRide-01#69]
## 목적
> 신규 유저 로그인 시 선택화면으로 이동하지 않고 내 FTTI화면으로 이동하는 오류를 수정하기 위함.
## 작업 상세 내용
- [x] 오류 Fix

**Comment by Juri-Jang** [comment]
애뮬레이터, 실제 안드로이드 기기에서 접속 했을 땐 오류가 안남..
블루 스택에 문제인지 확인 필요

**Comment by Juri-Jang** [comment]
회원가입 -> FTTI 검사 안하고 실행 종료 -> 재접속 시 에러 발생하는 것으로 확인
회원가입은 했지만 FTTI 검사 안하고 종료한 경우에도, 재접속시 로그인 화면으로 이동하도록 수정하여 해결함 #86
