### ISSUE TITLE
Bug: Cozy Elegance image not loading

### ISSUE THREAD

**Issue by Fairy-Slayer** [CSID-DGU/2024-1-OSSProj-ComfyRide-01#71]
## 목적
> "내FTTI"에서 Cozy Elegance의 경우 이미지가 로딩되지 않는 오류를 수정하기 위함
## 작업 상세 내용
- [ ] Bug fix

**Comment by Juri-Jang** [comment]
DB에 해당 이미지 수정하여 해결함
